name: C/C++ CI

on:
  pull_request:
    branches:
      - v5.1.0

jobs:
  job_lintgit_check:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: checkout_to_v5.1.0
      run: git checkout v5.1.0
    - name: Run lintgit
      run: ./tools/lintgit origin/master $PWD

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: checkout_to_v5.1.0
      run: git checkout v5.1.0
    - name: configure
      run: mkdir build && cd build && cmake -DMLU=MLU270 .. && make -j
    - name: test
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/neuware/lib64 && ./build/bin/cnstream_core_test && ./build/bin/cnstream_test
